"""add_search_vector

Revision ID: 03a5c50d1454
Revises: 62e87ad92d3b
Create Date: 2026-01-13 13:06:49.181836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03a5c50d1454'
down_revision = '62e87ad92d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')

    # Backfill
    op.execute(
        "UPDATE notes SET search_vector = to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))"
    )

    # Create Trigger
    op.execute(
        """
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON notes FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(search_vector, 'pg_catalog.english', title, content);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tsvectorupdate ON notes")
    op.drop_index('ix_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_column('notes', 'search_vector')
    # ### end Alembic commands ###
