"""Add refresh tokens table

Revision ID: 62e87ad92d3b
Revises: 8e818d4e2ca9
Create Date: 2026-01-12 22:04:04.820307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e87ad92d3b'
down_revision = '8e818d4e2ca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
